site_name: FastAPI Admin
site_url: https://github.com/fastapi-admin/fastapi-admin
repo_url: https://github.com/fastapi-admin/fastapi-admin
site_description: A fast admin dashboard based on FastAPI and TortoiseORM with tabler ui, inspired by Django admin.
repo_name: fastapi-admin/fastapi-admin
site_author: long2ice
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: deep purple
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlight
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
nav:
  - index.md
  - Getting Started:
      - getting_started.md
  - Pro Features:
      - pro/sponsor.md

extra:
  alternate:
    - name: English
      link: /latest/en/
      lang: en
    - name: 简体中文
      link: /latest/zh/
      lang: zh
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/long2ice

copyright: Copyright &copy; 2021 long2ice

plugins:
  - mike:
      version_selector: true
  - i18n:
      default_language: en
      languages:
        en: English
        zh: 简体中文
  - git-revision-date-localized:
      type: date
