[tool.poetry]
name = "fastapi-admin"
version = "0.2.6"
description = "Fast Admin Dashboard based on fastapi and tortoise-orm and rest-admin."
authors = ["long2ice <long2ice@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
tortoise-orm = "*"
aiomysql = "*"
python-dotenv = "*"
uvloop = "*"
python-rapidjson = "*"
fastapi = {version = "*", extras = ["all"]}
aiosqlite = "*"
passlib = "*"
bcrypt = "*"
pyjwt = "*"
xlsxwriter = "*"
colorama = "*"
prompt_toolkit = "*"

[tool.poetry.dev-dependencies]
taskipy = "*"
asynctest = "*"
flake8 = "*"
isort = "*"
black = "^19.10b0"
pytest = "*"
pytest-xdist = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.taskipy.tasks]
export = "poetry export -f requirements.txt --without-hashes > requirements.txt"
export-dev = "poetry export -f requirements.txt --dev --without-hashes > requirements-dev.txt"
