site_name: FastAPI Admin
site_url: https://github.com/fastapi-admin/fastapi-admin
repo_url: https://github.com/fastapi-admin/fastapi-admin
site_description: A fast admin dashboard based on FastAPI and TortoiseORM with tabler ui, inspired by Django admin.
repo_name: fastapi-admin/fastapi-admin
site_author: long2ice
theme:
  logo: https://fastapi.tiangolo.com/img/icon-white.svg
  favicon: https://fastapi.tiangolo.com/img/favicon.png
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to default mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlight
    - navigation.top
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
nav:
  - Getting Started:
      - getting_started/index.md
      - getting_started/installation.md
      - getting_started/quickstart.md
  - Reference:
      - reference/index.md
  - Pro Version For Sponsor:
      - pro/index.md
      - pro/sponsor.md
      - pro/installation.md
extra:
  alternate:
    - name: English
      link: /
    - name: 简体中文
      link: /zh/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/long2ice

copyright: Copyright &copy; 2021 long2ice

plugins:
  - git-revision-date-localized:
      type: datetime
  - markdownextradata
