name: deploy
on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker buildx build -t docker.pkg.github.com/fastapi-admin/fastapi-admin/fastapi-admin:latest .
      - name: Publish image
        run: docker push docker.pkg.github.com/fastapi-admin/fastapi-admin/fastapi-admin:latest
  examples:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /root/fastapi-admin/
            docker-compose pull
            docker-compose up -d
