name: gh-pages
on:
  push:
    paths:
      - 'front/*'
      - '.github/workflows/gh-pages.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build
        env:
          PRODUCTION_BASE_URL: /
          BASE_URL: /
          VUE_APP_API_URL: https://api-fastapi-admin.long2ice.cn:8443
        run: |
          cd front
          npm install
          npm run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./front/dist
          cname: fastapi-admin.long2ice.cn