name: pypi
on:
  push:
    paths:
      - 'fastapi_admin/__init__.py'
      - '.github/workflows/pypi.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Build dists
        run: |
          python3 setup.py sdist

      - name: Pypi Publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /root/fastapi-admin/
            git pull
            supervisorctl restart fastapi-admin